import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "../types";

/** Export analysis result as a downloadable JSON file */
export function exportAsJSON(result: AnalysisResult): void {
  const blob = new Blob([JSON.stringify(result, null, 2)], {
    type: "application/json",
  });
  downloadBlob(blob, `nutrilens-analysis-${Date.now()}.json`);
}

/** Export analysis result as a styled PDF */
export function exportAsPDF(result: AnalysisResult): void {
  const doc = new jsPDF();
  const { total_nutrition: tn, foods, confidence_score, analysis_summary } = result;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(5, 150, 105); // brand-600
  doc.text("NutriLens", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("AI-Powered Nutrition Analysis", 14, 27);

  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, 30, 196, 30);

  // Summary section
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("Nutrition Summary", 14, 40);

  doc.setFontSize(28);
  doc.text(`${tn.calories} kcal`, 14, 54);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Confidence: ${Math.round(confidence_score * 100)}%`, 14, 62);
  
  // Wrap analysis summary
  const summaryLines = doc.splitTextToSize(analysis_summary, 180);
  doc.text(summaryLines, 14, 70);

  const summaryEndY = 70 + summaryLines.length * 5;

  // Macros table
  autoTable(doc, {
    startY: summaryEndY + 8,
    head: [["Macro", "Amount", "Daily %"]],
    body: [
      ["Protein", `${tn.protein_g.toFixed(1)}g`, `${Math.round((tn.protein_g / 50) * 100)}%`],
      ["Carbs", `${tn.carbs_g.toFixed(1)}g`, `${Math.round((tn.carbs_g / 300) * 100)}%`],
      ["Fat", `${tn.fat_g.toFixed(1)}g`, `${Math.round((tn.fat_g / 65) * 100)}%`],
      ["Fiber", `${tn.fiber_g.toFixed(1)}g`, `${Math.round((tn.fiber_g / 25) * 100)}%`],
    ],
    headStyles: {
      fillColor: [5, 150, 105],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 10 },
  });

  // Food breakdown table
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY ?? summaryEndY + 60;

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Food Breakdown", 14, finalY + 12);

  autoTable(doc, {
    startY: finalY + 16,
    head: [["Food", "Portion", "Calories", "Protein", "Carbs", "Fat", "Fiber"]],
    body: foods.map((f) => [
      f.name,
      f.estimated_portion,
      `${f.calories}`,
      `${f.protein_g.toFixed(1)}g`,
      `${f.carbs_g.toFixed(1)}g`,
      `${f.fat_g.toFixed(1)}g`,
      `${f.fiber_g.toFixed(1)}g`,
    ]),
    headStyles: {
      fillColor: [5, 150, 105],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by NutriLens on ${new Date().toLocaleString()}`,
    14,
    pageHeight - 10,
  );

  doc.save(`nutrilens-analysis-${Date.now()}.pdf`);
}

/** Share analysis (Web Share API with fallback to clipboard) */
export async function shareResults(result: AnalysisResult): Promise<boolean> {
  const text = formatShareText(result);

  if (navigator.share) {
    try {
      await navigator.share({ title: "NutriLens Analysis", text });
      return true;
    } catch (error) {
      console.error("Web Share API failed:", error);
      // User cancelled or share failed — fall through to clipboard
    }
  }

  // Fallback: copy to clipboard
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error("Clipboard write failed:", error);
    return false;
  }
}

function formatShareText(result: AnalysisResult): string {
  const { total_nutrition: tn, foods, analysis_summary } = result;
  const foodNames = foods.map((f) => f.name).join(", ");
  return `🍽️ NutriLens Analysis

Foods: ${foodNames}
Total: ${tn.calories} kcal
Protein: ${tn.protein_g.toFixed(1)}g | Carbs: ${tn.carbs_g.toFixed(1)}g | Fat: ${tn.fat_g.toFixed(1)}g | Fiber: ${tn.fiber_g.toFixed(1)}g

${analysis_summary}

Analyzed with NutriLens — AI-powered nutrition estimator`;
}

/* ── Helpers ── */

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
